hctnm1/Hacky-Py

codes/roman-to-numeral.py
=> roman-to-numeral.py

codes/lock_files.py
Added python program that enables users to password protect their files/folders, in their windows system. It used XOR encryption techniques to encrypt the files.
=> Add `lock_files.py`.

codes/tic-tac-toe.py
A simple cli implementation of the classic tic-tac-toe game.
=> Add `tic-tac-toe.py`.

codes/imageCompression.py
Before Compression:
After compression:
=> code for image compression added

codes/internetspeedtest.py
Hey I have made a python program to check internet speed
=> Internet Speed Test

codes/GrayCode_sequence_BitManupulation.py
=>  added a Bit manupulation code

codes/minesweeper.py
Added a program to play Minesweeper in the terminal!
It may not have a GUI, or even colour, but it's still better than the modern version of Microsoft Minesweeper!
=> created minesweeper.py

codes/rockpaper.py
Added a python program to play Rock, Paper, Scissor with computer.
=> Add rockpaper python program

codes/ASCII.py
python script which Print the ASCII Value  of input key
=> add ASCII.py

codes/TicTacToe.py
=> Tic Tac Toe using python. Please Rev & merge and also add hacktoberfest Label while accepting it.

codes/BinSearch.py
=> Binary Search Using python with explaination. 

codes/merge_sort.py
The other merge sort is an algorithm whereas this is a complete python code.
=> Adding merge_sort.py(Full working program).

codes/AudioExtractor.py
Python program to extract audio from video.
=> Added AudioExtractor.py

codes/AlarmClockGUI.py
Created a GUI version of Alarm Clock with essential features using Tkinter.
=> Added AlarmClockGUI.py

codes/Kadane's_Algo_py.py
Kadane's Algorithm cpp
Thankyou ^_^
=> Kadane's Algorithm cpp (Please merge and add hacktoberfest tag)

codes/QRLink.py
A Tkinter based GUI QR code generator which only accepts valid URLs
=> Added QRLink.py

codes/keylogger.py
adding a basic keylogger I made as a contribution for hacktober hopefully this will count as a valid contribution
=> add basic keylogger for hacktoberfest

codes/birthday.py
=> birthday.py

codes/Rock Paper Scissor.py
=> Added RPS Game written in Python

codes/BFS_Traversal.py
=> Added python program for BFS traversel

codes/reverse_linked_list.py
O/P:
Input : Head of following linked list  
1->2->3->4->NULL
Output : Linked list should be changed to,
4->3->2->1->NULL
=> Python Program to Reverse a linked list

codes/Naive_Bayes.ipynb
=> Added Naive Bayes Algo. used in ML
